[package]
name = "Máxima Tech"
description = "App de acesso remoto Máxima Tech"
identifier = "com.maximatech.maxviewer"
version = "1.0"

[server]
api = "http://maxviewer.maximatech.com.br:21114"
key = "sTbpuncgIt6Uh0cmHquHMgNVCorP4y4t00nJmPhrxfE="
relay = "maxviewer.maximatech.com.br:21117"
id = "maxviewer.maximatech.com.br"

[branding]
logo = "assets/logo.png"
icon = "assets/icon.png"
splash = "assets/logo.png"
